# https://taskfile.dev

version: '3'

vars:
  DB_PATH: '{{default "index.duckdb" .DB_PATH}}'
  EMBEDDING_MODEL: '{{default "cl-nagoya/ruri-v3-310m" .EMBEDDING_MODEL}}'
  RERANK_MODEL: '{{default "cl-nagoya/ruri-v3-reranker-310m" .RERANK_MODEL}}'

tasks:
  default:
    desc: "Display list of available tasks"
    cmds:
      - task --list
    silent: true

  setup:
    desc: "Set up dependencies"
    cmds:
      - uv pip compile -o requirements.txt requirements.in
      - uv pip compile -o requirements-dev.txt requirements-dev.in
      - uv pip sync requirements.txt requirements-dev.txt

  format:
    desc: "Format code"
    cmds:
      - black src tests

  lint:
    desc: "Lint code"
    cmds:
      - ruff check src tests
      - mypy src

  test:
    desc: "Run tests"
    cmds:
      - pytest -q --cov=src --cov-fail-under=80

  ci:
    desc: "Run CI tasks (lint + test)"
    deps: [lint, test]

  docker:build:
    desc: "Build Docker image"
    cmds:
      - docker build -t duckdb-hybrid-doc-search:latest .

  docker:run:
    desc: "Run Docker image"
    cmds:
      - docker run --rm -it duckdb-hybrid-doc-search:latest {{.CLI_ARGS}}
    vars:
      CLI_ARGS: '{{default "" .CLI_ARGS}}'

  dev:setup:
    desc: "Set up development environment"
    cmds:
      - python -m venv .venv
      - echo "To activate the virtual environment, run 'source .venv/bin/activate'"
      - task setup
      - pip install -e .

  run:index:
    desc: "Create document index"
    cmds:
      - duckdb-hybrid-doc-search index {{.DIRS}} --db {{.DB_PATH}} --embedding-model {{.EMBEDDING_MODEL}} {{.ARGS}}
    vars:
      DIRS: '{{default "docs/" .DIRS}}'
      ARGS: '{{default "" .ARGS}}'
      # Example: ARGS="--trim-path-prefix /app/"

  run:serve:
    desc: "Start MCP server with specified transport"
    cmds:
      - duckdb-hybrid-doc-search serve --db {{.DB_PATH}} --rerank-model {{.RERANK_MODEL}} --transport {{.TRANSPORT}} {{if eq .TRANSPORT "streamable-http"}}--host {{.HOST}} --port {{.PORT}} --path {{.PATH}}{{end}} {{.ARGS}}
    vars:
      TRANSPORT: '{{default "stdio" .TRANSPORT}}'
      HOST: '{{default "127.0.0.1" .HOST}}'
      PORT: '{{default "8765" .PORT}}'
      PATH: '{{default "/mcp" .PATH}}'
      ARGS: '{{default "" .ARGS}}'

  run:search:
    desc: "Run document search"
    cmds:
      - duckdb-hybrid-doc-search search --db {{.DB_PATH}} --rerank-model {{.RERANK_MODEL}} {{.ARGS}}
    vars:
      ARGS: '{{default "" .ARGS}}'
